AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CD Demo Lambda
Resources:
  LF1Photos:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: LF1Photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./Lambdas/LF1/lambda_function.py
      Description: "Lambda to search photos"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::907971805121:role/service-role/LF1Photos-role-jht0psqt"
      Environment:
        Variables:
          REGION: us-east-1
  LF2Photos:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: LF2Photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./Lambdas/LF2/lambda_function.py
      Description: "Lambda to index photos"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::907971805121:role/service-role/LF2Photos-role-to42lmsk"
      Environment:
        Variables:
          REGION: us-east-1